# Generated by Django 5.1.7 on 2026-03-14 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_initial'),
        ('templates_engine', '0003_seed_builtin_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='entries.entry')),
                ('template_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_sections', to='templates_engine.templatesection')),
            ],
            options={
                'db_table': 'entries_entrysection',
                'unique_together': {('entry', 'template_section')},
            },
        ),
    ]
